redir-port: 7892
tproxy-port: 7895
mixed-port: 7890
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874 # DNS 服务监听
  prefer-h3: true # 是否开启 DOH 的 http/3
  enhanced-mode: fake-ip # Clash 的 DNS 处理模式
  fake-ip-range: 198.18.0.1/16 # fakeip 下的 IP 段设置
  fake-ip-filter: # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
    - '*.lan'
    - '+.local'
    - localhost.ptlogin2.qq.com
  default-nameserver: # 默认 DNS, 用于解析 DNS 服务器 的域名. 必须为 IP, 可为加密 DNS
    - https://120.53.53.53/dns-query
    - tls://120.53.53.53
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  nameserver-policy:
    'geosite:cn,private':
      - tls://120.53.53.53
      - tls://223.5.5.5:853
      - https://doh.pub/dns-query
    'geosite:geolocation-!cn': 
      - tls://8.8.4.4
      - https://1.0.0.1/dns-query
  # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  nameserver:
    - tls://120.53.53.53
    - tls://223.5.5.5:853
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信
  # 配置 fallback 后默认启用 fallback-filter,geoip-code 为 cn
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://1.1.1.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://dns.oszx.co/dns-query
    - https://jp.tiar.app/dns-query
    - https://jp.tiarap.org/dns-query
    - https://dns.oszx.co/dns-query
    - tls://8.8.4.4
    - tls://1.1.1.1
  # 后备域名解析服务器筛选，满足条件的将使用 fallback 结果或只使用 fallback 解析
  fallback-filter:
    geoip: true
    geoip-code: CN # geoip-code 配置的国家的结果会直接采用，否则将被视为被污染,采用 fallback 结果
    geosite: # geosite 列表的内容被视为已污染，匹配到 geosite 的域名，将只使用 fallback解析，不去使用 nameserver
      - gfw
    ipcidr: # 这些网段的结果会被视为污染，nameserver 解析出这些结果时将会采用 fallback 的解析结果
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain: # 这些域名被视为已污染，匹配到这些域名，会直接使用 fallback 解析，不去使用 nameserver
      - '+.google.com'
      - "+.youtube.com"
      - "+.facebook.com"
      - "+.meta.com"
      - "+.reddit.com"
      - "+.netflix.com"
      - "+.hulu.com"
      - "+.disneyplus.com"
      - "+.openai.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
