mixed-port: 7890
port: 7891
socks-port: 7893
redir-port: 7892
tproxy-port: 7895
mode: rule
log-level: info
ipv6: false # 内核不接受 IPv6 流量
keep-alive-interval: 30 # 控制 Clash 发出 TCP Keep Alive 包的间隔，减少移动设备耗电问题的临时措施。

# ============================================
# 允许局域网的其他设备经过 Clash 的代理端口访问互联网
allow-lan: true 
# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"

# ============== Geoip ======================
# 更改geoip使用文件,mmdb或者dat,可选 true/false,true为dat,此项有默认值 false
geodata-mode: false

# GEO文件加载模式
# 可选的加载模式如下
# standard：标准加载器
# memconservative：专为内存受限(小内存)设备优化的加载器(默认值)
geodata-loader: memconservative

geo-auto-update: true # 自动更新 GEO
geo-update-interval: 24 # 更新间隔,单位小时

# 自定 GEO 下载地址
geox-url:
#   geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#   geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

# 自定义外部资源下载时使用的的UA,默认为 clash.meta
# global-ua: clash.meta
# ==========================================

# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint。
# 目前支持开启 TLS 传输的 TCP/grpc/WS/HTTP , 支持协议有 VLESS,Vmess 和 trojan.
# global-client-fingerprint: random


# 在 Clash 官方中，profile 应为扩展配置，但在 Clash.meta, 仅作为缓存项使用
#profile:
#  store-selected: true # 储存 API 对策略组的选择，以供下次启动时使用
#  store-fake-ip: true # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874 # DNS 服务监听
  prefer-h3: true # 是否开启 DOH 的 http/3
  enhanced-mode: fake-ip # Clash 的 DNS 处理模式
  fake-ip-range: 198.18.0.1/16 # fakeip 下的 IP 段设置
  fake-ip-filter: # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
    - '*.lan'
    - '+.local'
    - localhost.ptlogin2.qq.com
  default-nameserver: # 默认 DNS, 用于解析 DNS 服务器 的域名. 必须为 IP, 可为加密 DNS
    - 1.1.1.1
    - 114.114.114.114
    - 223.5.5.5
  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  nameserver-policy:
    'geoip:cn,private':
      - tls://120.53.53.53
      - tls://223.5.5.5:853
      - https://doh.pub/dns-query
    'geosite:geolocation-!cn':
      - https://dns.google/dns-query
      - https://1.0.0.1/dns-query
  # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  nameserver:
    - tls://120.53.53.53
    - tls://223.5.5.5:853
    - https://dns.alidns.com/dns-query
  # 代理节点域名解析服务器，仅用于解析代理节点的域名
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信
  # 配置 fallback 后默认启用 fallback-filter,geoip-code 为 cn
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://1.0.0.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://jp.tiarap.org/dns-query
  # 后备域名解析服务器筛选，满足条件的将使用 fallback 结果或只使用 fallback 解析
  fallback-filter:
    geoip: true
    geoip-code: CN # geoip-code 配置的国家的结果会直接采用，否则将被视为被污染,采用 fallback 结果
    ipcidr: # 这些网段的结果会被视为污染，nameserver 解析出这些结果时将会采用 fallback 的解析结果
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain: # 这些域名被视为已污染，匹配到这些域名，会直接使用 fallback 解析，不去使用 nameserver
      - '+.google.com'
      - "+.youtube.com"
      - "+.facebook.com"
      - "+.meta.com"
      - "+.reddit.com"
      - "+.netflix.com"
      - "+.hulu.com"
      - "+.disneyplus.com"
      - "+.openai.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
